name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 5.13.0

dependencies:
  # artemis: 7.11.0-beta.1
  async: 2.11.0
  auto_route: 7.5.0
  # go_router: ^6.0.1
  cached_network_image: 3.2.1
  cupertino_icons: 1.0.3
  dartx: 1.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.3.6
  hooks_riverpod: 2.3.6
  riverpod_annotation: 2.1.1
  flutter_hooks: 0.18.6
  flutter_local_notifications: 13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.8.4
  flutter_svg: 1.1.6
  get_it: 7.6.0
  infinite_scroll_pagination: 3.2.0
  tuple: 2.0.2
  injectable: 2.1.2
  meta: 1.9.1
  rxdart: 0.27.7
  intl: 0.18.0
  mime: 1.0.1
  package_info_plus: 3.0.3
  device_info_plus: 8.1.0
  path_provider: 2.0.7
  timezone: 0.9.0
  url_launcher: 6.0.17
  flutter_cache_manager: 3.3.0
  decimal: 2.1.0
  connectivity_plus: 3.0.3
  dio: 5.2.1+1
  dio_cookie_manager: 3.1.0
  encrypted_shared_preferences: 2.0.0
  gql: 0.14.0
  gql_dio_link: 0.3.0
  gql_exec: 0.4.3
  gql_link: 0.5.1
  graphql_flutter: 5.1.2
  json_annotation: 4.8.1
  # location: 4.4.0 # ERROR: project ':location' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20
  objectbox: 2.1.0
  objectbox_flutter_libs: 2.1.0
  fast_immutable_collections: ^8.1.1
  equatable: ^2.0.3 # Allows value based equality for our classes e.g Eat() == Eat() is true
  flutter_easyloading: ^3.0.5
  flutter_form_builder: 9.0.0
  form_builder_validators: 9.0.0
  form_builder_phone_field: ^2.0.1
  android_id: ^0.1.3+1
  dropdown_button2: ^2.0.0
  flutter_udid: 2.0.1
  # firebase
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4
  firebase_dynamic_links: ^5.3.3
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^4.4.0+1

dev_dependencies:
  auto_route_generator: 7.1.1
  riverpod_generator: 2.2.3
  riverpod_lint: 1.3.2
  build_runner: 2.4.5
  custom_lint: 0.4.0
  dart_code_metrics: 5.7.5
  flutter_gen_runner: 5.3.1
  flutter_launcher_icons: 0.13.1
  flutter_lints: 2.0.1
  flutter_native_splash: 2.2.19
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.6
  mocktail: 0.3.0
  intl_utils: 2.8.2
  json_serializable: 6.7.0
  objectbox_generator: 2.1.0

# Config generate when build
flutter_gen:
  output: lib/resources/generated
  # line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
    # - assets/jsons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/resources/generated
  arb_dir: lib/resources/l10n

objectbox:
  output_dir: data/repository/source/database/generated
